services:
  - type: web
    name: youtube-hls-viewer
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    branch: main
    autoDeploy: true
