services:
  - type: web
    name: lentrance-reader
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: YOUTUBE_API_KEY
        sync: false
